OPT?=-O
PREFIX?=arm-unknown-eabi-
CC=$(PREFIX)gcc
LD=$(PREFIX)ld
CFLAGS?=$(OPT) -mcpu=cortex-m4 -mthumb -g -lgcc -static -nostartfiles -Iinclude
LD_FLAGS?=-T linker/linker_script.ld -nostdlib --cref -Map linker/main.map -static


all: _$(PREFIX)_obs/main.elf

_$(PREFIX)_obs/main.bin: main.elf
	$(PREFIX)objcopy -O binary _$(PREFIX)_obs/main.elf _$(PREFIX)_obs/main.bin

flash: main.bin
	st-flash write _$(PREFIX)_obs/main.bin 0x8000000

clean:
	rm -rf _*_obs

genmake:
	./genmake.pl > Makefile
